### ISSUE TITLE
Model with wildcard field name?

### ISSUE THREAD

**Issue by Quantisan** [noirbizarre/flask-restplus#172]
I am expecting a dict like so:

```
{
  "personA": 1,
  "personB": 2,
  ...
}
```

Is there a way to specify a wildcard for a field like so?

```
api.model('MyModel', {
    Any: fields.Integer
})
```

**Comment by 4c74356b41** [comment]
Actually I'm pretty interested in this one also. Since I'm expecting a dict, and have no idea how large is it going to be. I've worked around that with fields.Raw, but that doesn't seem all that great!

**Comment by ziirish** [comment]
Hi,

I've been working on such a feature for a project of mine.
I probably won't make a pull request since I have "monkey-patched" several parts of Flask-Restplus. Besides, it's not that easy to implement and I'm not sure this will cover everyone's need, but I'll share my implementation here if you like.

It works like this:

```python
data = {
  'aa': '1',
  'ab': 12.0,
  'ba': 5
}
wildcard = fields.Wildcard(field.Integer)
fields = api.model('MyModel', {
    'a*': wildcard
})
marshal(data, fields)
```

Resulting in:

```python
{
  'aa': 1,
  'ab': 12
}
```

You need to declare the `wildcard` field outside of your model since the object needs to keep a track of the index/key it is currently working on.

**Comment by ziirish** [comment]
My code is [here](https://github.com/ziirish/burp-ui/blob/master/burpui/api/custom/my_fields.py#L98)
And [here](https://github.com/ziirish/burp-ui/blob/master/burpui/api/servers.py#L106) is how to use it.

Unfortunately, for this code to work I had to patch the `Nested` fields, the `marshalling` and the `Namespace`. Besides, you cannot use the `Wildcard` with other fields because `models` are not ordered and you may end up with mixed results.

**Comment by ziirish** [comment]
This feature has finally been merged in master and will be part of the next release so I'm closing this issue.
