### ISSUE TITLE
Serve Swagger UI as HTML, keeping JSON for everything else

### ISSUE THREAD

**Issue by vargavince91** [noirbizarre/flask-restplus#188]
I have a REST API where I set the response class' type to `application/json`. Unfortunately this sets the `Content-Type` for the Swagger UI, so the page doesn't render in browsers.

Is there a way to change the Swagger UI Content type to html, while keeping JSON for the rest of the app? What am I missing here?

```py
class JsonResponse(Response):
    default_mimetype = 'application/json'

# bp is a blueprint: bp = Blueprint(bla bla, params...)
api = Api(bp, version='1.0', title='API', description='Simple API', doc='/doc/')
# default_mediatype='text/html' didn't help

app = Flask(__name__)
app.register_blueprint(bp)
app.response_class = JsonResponse
```

Thank you for your help.

**Comment by ziirish** [comment]
Hello,

What is the purpose of `JsonResponse`? Your `api` Blueprint will return `application/json` by default when appropriate.
The problem you encounter is that the Swagger *application* is served by `Flask`, but since you force the `Content-type` for everything that is returned by Flask, you broke Swagger UI as well.

**Comment by vargavince91** [comment]
What do you mean Blueprint returns JSON when appropriate? I removed `app.response_class = JsonResponse` and it returned the text as `text/html`.

The purpose of `JsonResponse` is to set the `Content Type` to `application/json`. Without the `app.response_class = JsonResponse` the type of the response is:

```
Content-Type: text/html; charset=utf-8
```

Example cURL without `app.response_class = JsonResponse`
```
$ curl --verbose --header "Accept: application/json" http://127.0.0.1:8000/hello
> Accept: application/json
< Content-Type: text/html; charset=utf-8
```

Example cURL with `app.response_class = JsonResponse`:
```
$ curl --verbose --header "Accept: application/json" http://127.0.0.1:8000/hello
> Accept: application/json
< Content-Type: application/json

OR

curl --verbose http://127.0.0.1:8000/hello
> Accept: */*
< Content-Type: application/json
```

Do you have any other hints? How could I solve this? We are developing a REST+JSON API that I'd like to document and test with the Swagger UI (that should be served as HTML).

**Comment by ziirish** [comment]
With you `JsonResponse` class, you force `Flask` to return `application/json` for **everything**, including the Swagger *application*.

I'm pretty sure this is not what you want since such configuration forbids you to serve HTML/CSS/JS content.

Now in your initial code you have this:

```.python
# bp is a blueprint: bp = Blueprint(bla bla, params...)
api = Api(bp, version='1.0', title='API', description='Simple API', doc='/doc/')
# default_mediatype='text/html' didn't help

app = Flask(__name__)
app.register_blueprint(bp)
```

Where `bp` is probably something like: `bp = Blueprint('api', __name__, url_prefix='/api')`

This way, everything under `/api` will be handled by `Flask-Restplus` which will return `application/json` Content-type most of the time.

**Comment by ziirish** [comment]
Example with an application that does not force the `Content-type`:

```
curl -I --header "Accept: application/json" https://example.org/api/some/end/point
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 03 Aug 2016 08:34:17 GMT
Content-Type: application/json
Content-Length: 223
Connection: keep-alive
Vary: Accept-Encoding

curl -I --header "Accept: application/json" https://demo.ziirish.me/hello         
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 03 Aug 2016 08:34:51 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 10375
Connection: keep-alive
Vary: Accept-Encoding
```

**Comment by vargavince91** [comment]
Got it, the problem was that, as I am refactoring a small API to use `restplus`, I was in a state between "Vanilla" Flask and Flask RESTPlus.

Flask RESTPlus does, indeed, by default respond with `Content-Type: application/json` (though afaik it has nothing to do with the Blueprint (that you mentioned), where I was looking for the issue), while still serving the Swagger UI as `text/html`.

Thank you for your help!
