### ISSUE TITLE
RequestParser doesn't handle booleans submitted as 'false' correctly

### ISSUE THREAD

**Issue by AndyMan1** [noirbizarre/flask-restplus#199]
When the RequestParser is given an argument of type `bool`, it parses _any_ value as `True` and only the absence of the parameter as `False`. If the argument  is default=`True`, it's impossible to actually get a false value.

Code demonstration:

``` python
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)
api = Api(app)

test_parser = api.parser()
test_parser.add_argument('foo', type=bool, default=False)
test_parser.add_argument('bar', type=bool, default=True)

@api.route('/hello')
class HelloWorld(Resource):
    @api.expect(test_parser)
    def get(self):
        args = test_parser.parse_args()
        return dict(args)

if __name__ == '__main__':
    app.run(debug=True) 
```

The swagger docs give you a nice dropdown of [blank], 'true', 'false'. Using it gives the following:
- `http://127.0.0.1:5000/hello`
  - `{"bar": true, "foo": false}`
- `http://127.0.0.1:5000/hello?foo=true&bar=true`
  - `{"bar": true, "foo": true}`
- `http://127.0.0.1:5000/hello?foo=false&bar=false`
  - `{"bar": true, "foo": true}`

Considering the generated swagger documentation tells you to use `foo=false`, the RequestParser should interpret the string 'false' as the boolean False. 

I'm guessing under the hood it's doing something like bool("false"), which evaluates as True?

Attempted using Python 2.7.5, flask-restplus both 0.8.6 and 0.9.2

**Comment by lucacome** [comment]
Any news on this?

**Comment by hugochinchilla** [comment]
I'm getting hit by this bug also.

But in my case I don't have a default value set.

If the argument in the querystring is missing I get `None`, but if the argument is `"true"` or `"false"` the parsed value is always `True`

**Comment by awiddersheim** [comment]
Instead of using Python's `bool` as the type you should be using Flask RESTPlus's `boolean` input:

```python
from flask import Flask
from flask_restplus import Resource, Api
from flask_restplus import inputs

app = Flask(__name__)
api = Api(app)

test_parser = api.parser()
test_parser.add_argument('foo', type=inputs.boolean)
test_parser.add_argument('bar', type=inputs.boolean, default=True)

@api.route('/hello')
class HelloWorld(Resource):
    @api.expect(test_parser)
    def get(self):
        args = test_parser.parse_args()
        return dict(args)

if __name__ == '__main__':
    app.run(debug=True)
```

This seems to work correctly for me.


Since Flask-RESTPlus's internals are still very much like Flask-RESTful at this point you might want to check their issue tracker as well for clues.

https://github.com/flask-restful/flask-restful/issues/488

Also, these inputs aren't really spelled out in the documentation anywhere and probably should be.

For example, here is some of the relevant docs from Flask-RESTful:

http://flask-restful-cn.readthedocs.io/en/0.3.5/extending.html?highlight=inputs#inputs
http://flask-restful-cn.readthedocs.io/en/0.3.5/api.html?highlight=inputs#module-inputs

**Comment by awiddersheim** [comment]
I did notice that `foo` in this example doesn't get show a default in swagger:

![image](https://cloud.githubusercontent.com/assets/3237256/22506949/0e485474-e851-11e6-94ff-591cd1f4ec37.png)

Since the default is set to `False`, when the swagger spec gets built it thinks it doesn't have a default.

Problem is here:

https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/reqparse.py#L272-L273

Instead of

```python
if self.default:
```

maybe it should be:

```python
if self.default is not None:
```

**Comment by noirbizarre** [comment]
You should use the `inputs` module @awiddersheim suggested.
I'll fix the `default=False` case.

**Comment by nickv2002** [comment]
Flask RestPlus has been replaced by Flask RestX
Specifically you should use this function for parsing bools: https://flask-restx.readthedocs.io/en/latest/api.html?highlight=boolean#flask_restx.inputs.boolean
