### ISSUE TITLE
Using JWT as auth

### ISSUE THREAD

**Issue by googley** [noirbizarre/flask-restplus#229]
Is there any way to authenticate with Json Web Token (Flask-JWT) ?

**Comment by r0hitsharma** [comment]
I have been able to integrate with both `Flask-JWT` and `Flask-JWT-Extended` by using the `@jwt_required` decorator in front of the Resource methods. (Adding the decorator globally for the config broke the documentation for me, so that's why I have it put on all the routes manually.)

The advantage of using `Flask-JWT-Extended` is that it allows you to setup the `/auth` route yourself, so you could document it as part of an Auth Resource if you so desire.

**Comment by grhawk** [comment]
@googley Sorry, I did not understand... where is the `@jwt_required` decorator coming from?

**Comment by mde-pach** [comment]
@grhawk `@jwt_required` came from `Flask-JWT` or `Flask-JWT-Extended` https://github.com/vimalloc/flask-jwt-extended
It's not a part of Flask RestPlus.

**Comment by grhawk** [comment]
@mde-pach Thank you! I solved the problem using `flask_httpauth` modifying the authentication to accept also the Header without the `Bearer` word.
