### ISSUE TITLE
Use auth_token_required decorator ,Response returned  was empty 

### ISSUE THREAD

**Issue by dshkwnds** [noirbizarre/flask-restplus#323]
At that time I was using the flask-security protected my api, I used the resource marshal_with auth_token_requried after the decorator, the response returned was empty 

response like this:

### CURL
 curl -X GET --header 'Accept: application/json' --header 'Authorization: WyIyMDIiLCIkNSRyb3VuZHM9NTM1MDAwJE4waGcuaW0zazNNL0Y3S0MkMWNUY0JqS0V6SHdoczdaZ3BsVDMzWWU3OEtSVmhTL2RWN2ZiQ2NJZHhrQiJd.DKN_rQ.am_iYgnuW0S89mncKQ-ZA1bEzJ4' 'http://localhost:5000/api/company/?page=1&per_page=10'

### Response Body 
 { }
### Request URL 
http://localhost:5000/api/company/?page=1&per_page=10
### Response Code 
200

I commented 44 lines and 45 lines in the marshalling file:
```python
    if mask:
          fields = apply_mask (fields, mask, skip = True)
```
The problem is solved, I do not know this is  a bug or I configured the problem?

This is my code:

```python
@ns.route('/')
class CompanyCollection(Resource):
    @auth_token_required
    @roles_required('user')
    @api.expect(pagination_arguments)
    #@api.header('Authorization', 'Token Code ', required=True)
    @api.marshal_with(page_of_company)
    def get(self):
        """
        Returns list of investment company.
        """
        args = pagination_arguments.parse_args(request)
        page = args.get('page', 1)
        per_page = args.get('per_page', 10)
        posts_query = DD_MGRCOMP_INFO.query
        posts_page = posts_query.paginate(page, per_page, error_out=True)

```

confing:
```python
      RESTPLUS_MASK_SWAGGER = True
      RESTPLUS_MASK_HEADER = 'Authorization'
```

**Comment by tyronjameshall** [comment]
I found this issue as well, the issue is a bit simpler than that it seems (the marshalling is hiding the failure from you if its the same as my issue, try something simple like this to see):

@api.route('/test')
class test(Resource):
    @http_auth_required #These Flask Security Annotations are causing flask rest plus to have a routing conflict of some kind if to hit the api up in postman or soapUi
    @roles_required('admin', 'module') #These Flask Security Annotations are causing flask rest plus to have a routing conflict of some kind if to hit the api up in postman or soapUi
    def get(self):
        return 'response', 201  # Response with code

Un-Authenticated:
    
<h1>Unauthorized</h1>
<p>The server could not verify that you are authorized to access the URL
    requested. You either supplied the wrong credentials (e.g. a bad password),
    or your browser doesn't understand how to supply the credentials required.
    </p>

Authenticated:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

Via Swagger:
![selection_132](https://user-images.githubusercontent.com/3232544/32894892-e4538890-cae6-11e7-875f-4c60c0de7c89.png)
