### ISSUE TITLE
Swagger header field in documentation not working correctly

### ISSUE THREAD

**Issue by ivarflakstad** [noirbizarre/flask-restplus#337]
Consider this minimal-ish example:

```python
from flask import Flask
from flask_restplus import Api, Resource


application = Flask(__name__)
api = Api(
    application,
    title='test header functionality',
)


@api.route('/test')
@api.header('Accept', 'Accept header!')
class TestResource(Resource):
    def get(self):
        return {'result': api.mediatypes()}



if __name__ == '__main__':
    application.run(debug=True)
```

Which results in the following bug in swagger:

![swagger](https://user-images.githubusercontent.com/3002216/31316481-b43cc828-ac2e-11e7-8aea-238866f943bd.png)

The problem must be in swagger itself, right? Should I open a issue there?

It works great with curl:

![curl](https://user-images.githubusercontent.com/3002216/31316506-3f2237ca-ac2f-11e7-9298-c445a880a5ff.png)

**Comment by naeioan** [comment]
I think you need to register the MIME type "application/javascript" ( check this http://flask-restful.readthedocs.io/en/0.3.5/extending.html ).
I think the only MIME type supported by default by Swagger is "application/json".
Look also in flask_restplus/api.py in the constructor:
DEFAULT_REPRESENTATIONS = [('application/json', output_json)]
self.representations = OrderedDict(DEFAULT_REPRESENTATIONS)

**Comment by ivarflakstad** [comment]
Why would it work with curl?

**Comment by naeioan** [comment]
In your example code, the output is normal in Swagger, because if you look at the implementation: default_mediatype='application/json', decorators=None.
The difference between Swagger in curl is exactly that :D , curl is not Swagger.
Look at how Swagger creates the documentation (http://docs.swagger.io/spec.html) in 5.2.2.1 Object Example:
{
  "apiVersion": "1.0.0",
  "swaggerVersion": "1.2",
  "basePath": "http://petstore.swagger.wordnik.com/api",
  "resourcePath": "/store",
  "produces": [
    "application/json"
  ],
Flask-rest+ changes the "produces" fields in the Swagger XML's based on the registered MIME representation.
Curl does not temper with that.  This is my opinion anyhow.
Curl and Swagger are clients and behave differently.

**Comment by ivarflakstad** [comment]
Of course curl and swagger behave differently, was never any doubt about that.
I did not know there was such an elaborate response content type scheme in swagger, so I treated it as I would any other header. For the project I am working on, it would be much easier to do it the way I intended, but I can make it work like this as well.
This solved my problem, thank you for the help! :+1:

**Comment by kenneho** [comment]
Is it the using the [@api.representation](https://flask-restplus.readthedocs.io/en/stable/_modules/flask_restplus/api.html#Api.representation) decorator you're referring to?
