### ISSUE TITLE
Please publish the .tar.gz for the latest version

### ISSUE THREAD

**Issue by iksaif** [noirbizarre/flask-restplus#515]
Looks like 0.11.0 only has a wheel file and no .tar.gz:
- https://pypi.org/simple/flask-restplus/
- https://pypi.org/project/flask-restplus/#files

This seems to be causing problems with `pex` when using the `--no-wheel` option.

Thanks !

**Comment by noirbizarre** [comment]
I'm curious: as `flask-restplus` does not rely on binaries nor compilation, why are you using `--no-wheel` to install it ?
If this this the same behavior as `pip`, you can use `--no-wheel` (actually this is now `--no-binary`) on a specific package (ie. `--no-binary faulty-package`)

(I'll publish the `.tar.gz` on the next soon to come releasebut this will be the first time since long ago as I try to produce pure python packages to avoid this kind of issues)
