### ISSUE TITLE
Namespace tags without attached resources are not hidden from the documentation

### ISSUE THREAD

**Issue by lextiz** [noirbizarre/flask-restplus#570]
[Docs](https://flask-restplus.readthedocs.io/en/stable/swagger.html#hiding-from-documentation) say that:

> Namespace tags without attached resources will be hidden automatically from the documentation.

Which is not not true. Steps to reproduce:
1. Create a namespace, that has a single resource implemented by class
1. Add the following annotation ```@my_namespace.route('/endpoint', doc=False)```
1. Swagger UI will have an empty entry for the namespace

**Comment by josephmcgovern-wf** [comment]
I would love to see this fixed as well.

**Comment by SteadBytes** [comment]
The behaviour described in the docs is correct, the issue here is that the `Resource` does exist on the namespace however the `doc=False` argument prevents it from being shown. If your namespace actually has no resources attached then it is hidden from the documentation:
```python
from flask import Flask

from flask_restplus import Api, Namespace, Resource


app = Flask(__name__)
api = Api(app)

namespace_with_resources = Namespace("Resources")
api.add_namespace(namespace_with_resources)

# your example
@namespace_with_resources.route("/foo", doc=False)
class MyResource(Resource):
    def get(self):
        return "foo"


namespace_without_resources = Namespace("No Resources")
api.add_namespace(namespace_without_resources)


if __name__ == "__main__":
    app.run(port=8080)
```

Swagger UI:
![image](https://user-images.githubusercontent.com/14834132/55085472-a41e1300-509e-11e9-8e2a-645d72bba15c.png)

The `namespace_without_resources` is hidden from the documentation as it has no resources registered on it. The `namespace_with_resources` is shown because it does have resources on it. Does that explain the behaviour? :smile: 

However, this does highlight an issue that if there are no resources attached to a namespace that have `doc=True`, it should also be hidden as if it had no resources attached. If you are happy with this explanation, I would like to close this issue. I will create a separate issue for the problem I just described and it will be addressed soon :+1:

**Comment by lextiz** [comment]
Hi @SteadBytes, this makes perfect sense. We could also rename this issue to store the conversation in a single place.

**Comment by SteadBytes** [comment]
@lextiz , since this issue is not actually about the one I described I would like to create a new one for easier organisation. We are currently having a bit of a 'bug hunt' and as such will be clearing out issues and organising new ones into a roadmap for development. I will create a new issue with the example I just posted and will link it here as well :+1:

**Comment by SteadBytes** [comment]
@lextiz here is the issue #615

**Comment by SteadBytes** [comment]
@lextiz @josephmcgovern-wf FYI a fix for the issue we discovered here has now been merged into master from #625 :+1: Thank you for helping discover the problem :smile:

**Comment by lextiz** [comment]
Thanks for the fix!

**Comment by SteadBytes** [comment]
@josephmcgovern-wf We're hoping to get a release out in the next week or so with a collection of various bug fixes and improvements :+1: . Might be worth keeping an eye on Gitter for updates :smile:

**Comment by lextiz** [comment]
Hi @SteadBytes, thanks again for fixing the issue. Do you know approximately when the fix to this issue will be released? I have read some posts on Gitter but did not find any upcoming release discussions.

**Comment by SteadBytes** [comment]
Hi @lextiz, I apologise for the delay on this. Currently the lead maintainer of the project @noirbizarre is taking a break due to the recent birth of his son :smile: Unfortunately us other maintainers don't have the ability to push new releases to PyPI so we need to wait for @noirbizarre to return to able to push out all the features/fixes we've pushed into `master` over the past few weeks. Again, I apologise on the delay, I will try to get in touch with @noirbizarre to see how he is feeling about returning :+1:

**Comment by lextiz** [comment]
@SteadBytes Thanks for the update. @noirbizarre Félicitations!
