### ISSUE TITLE
KeyError: 'view_class' when I try to run the api app created with flask_restplus

### ISSUE THREAD

**Issue by PyDataBlog** [noirbizarre/flask-restplus#632]
Here's the code to reproduce the error:

```py
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)
api = Api(app=app)


@api.route('/')
class Root(Resource):
    def get(self):
        return {'message': 'it works'}, 200


@api.route('/test')
class Test(Resource):
    def post(self):
        pass


if __name__ == '__main__':
    app.run(debug=True)
```

What did I do wrong?

**Comment by SteadBytes** [comment]
The problem here is caused by the `Root` class, if you rename that to something else it works fine. Flask-RESTPlus registers a view named `root` during initialisation - [source](https://github.com/noirbizarre/flask-restplus/blob/61d7fbf755c342ff5ffc6f9ce5e7b11623ff804e/flask_restplus/api.py#L254). 

Do you think it would be beneficial to produce a more specific error in this case?

**Comment by PyDataBlog** [comment]
Changing the name fixes the issue indeed. All good now. Thanks for your time. Keep up the good work

**Comment by SteadBytes** [comment]
Thank you!
