### ISSUE TITLE
[FEATURE IDEA] Add pedantic library for documentation and model validation

### ISSUE THREAD

**Issue by tincumagic** [noirbizarre/flask-restplus#715]
IDEA
We should absolutely add pedantic library usage to Flask-resplus.
 It's a new library for generating data-model for validation and generating documentation in the way FastAPI library already does. It requires python > 3.5 with typing library and type hints.

**Comment by SteadBytes** [comment]
Thanks for the suggestion, currently we are trying to figure out the next steps for the project. For a long time it has been assumed that we would move over to using Marshmallow, however this will be taken into consideration. For now I will close the issue as we are unlikely to implement anything yet, in addition dropping support for python < 3.5 is a major change for the library and I don't think it's a good idea just yet due to Flask still supporting Python 2.

Love the enthusiasm though! :smile:
