### ISSUE TITLE
`werkzeug.utils.cached_property` is deprecated

### ISSUE THREAD

**Issue by shnela** [noirbizarre/flask-restplus#758]
We use [`werkzeug.utils.cached_property`](https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/fields.py#L17) which is depracated:  
>.../site-packages/flask_restplus/fields.py:17: DeprecationWarning:
> The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.

**Comment by YellowFoxH4XOR** [comment]
it is already updated in the master branch as :

 **werkzeug.utils import cached_property**

Please check 😃

**Comment by MartinThoma** [comment]
There was no release since this was done, though: https://pypi.org/project/flask-restplus/#history

**Comment by MartinThoma** [comment]
Might be interesting as well: In Python 3.8 you can simply do

    from functools import cached_property

**Comment by j5awry** [comment]
flask-restplus is no longer maintained. The current maintainers have not been able to produce releases due to lack of pypi privileges. As such, we have created an official fork, flask-restx. On github at python-restx/flask-restx. It's a drop in replacement and has a fix.

Do not expect any releases from flask-restplus in the near future
