### ISSUE TITLE
Support vendor fields

### ISSUE THREAD

**Issue by noirbizarre** [noirbizarre/flask-restplus#97]
Swagger allow to add custom/vendor fields at every level: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions

flask-restplus should support declaring vendor fields.

@Kelvinm you said in #44 that you have some local modification on the subject. Do you mind to share them ?

**Comment by Kelvinm** [comment]
Hi Axel,

Good to hear form you.  I have the code at work. I would be happy to share,
maybe on Monday or Tuesday I'll try to get the changes to you with a pull
request..

**Comment by noirbizarre** [comment]
@Kelvinm I'm still interested in you work to see what can I take.

**Comment by Kelvinm** [comment]
Hi Axel,
Will do my best to get them to you again and not let it fall into the ether.

**Comment by harishkashyap** [comment]
@Kelvinm I am interested in this too!

**Comment by dmulter** [comment]
I need this badly too. My use case is generating a Swagger definition that can be imported into Amazon API Gateway. I would like to specify something like the following on any Swagger object:

@api.doc(x={amazon-apigateway-integration": {'type': 'http', 'httpMethod': 'GET',...}})

It would then extend the Swagger object with a field called "x-amazon-apigateway-integration" along with the specified JSON. There are lots more AWS extensions defined here: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

This approach should be extensible to any other vendor extensions.I'm also open to other styles for specifying the vendor extension parameter.

**Comment by Kelvinm** [comment]
I have that as well.  Ok, for real this time I'll make the pull request by
the end of the week as long as its approved by my managers.

@api.doc(parser=_parser, tags=['mytags'], x_VendorTag={'foo':'bar'})

**Comment by bedge** [comment]
Any update on this? 
Considering picking up this project for API gateway integration work with flask.
It looks ideal, but the lack of extension support is a concern.

**Comment by mikekitur** [comment]
hi guys, any plan for next release?

**Comment by Kelvinm** [comment]
I haven't had a chance to get the unittests passing with Travis but I plan
on coming back to it someday in the near future.  I would love to be able
to contribute back to this.

**Comment by kkrynitski** [comment]
I also need this feature. I took the code from the above PR https://github.com/noirbizarre/flask-restplus/pull/163/files#r60707743, and updated to fix unit test failures as well as address my needs. Thanks to @kmalyar-tic for the inspiration.
 
Specifically, my changes include:
-          Basic support for vendor extension fields.
-          Limited template support for dynamic fields.
 
Regarding the last item, I need to embed the absolute URL in the swagger json output in order to configure the AWS API GW. As there was no existing convention for this I elevated to go with the mustache template format "{{tag name}}" to identify the fields to be replaced at runtime.
There is no dependency on mustache, only using it's template convention.
 
The only dynamic parameter currently supported is the {{flask.fields.url.external}} (in my project I have other parameter and other procedure to substitute it with EP url)  which is replaced with the external url address (useful during development and testing process), which allows you do to the following:
  

```
@api.route('/api')
class Dump(Resource):
    """Dump API spec in swagger API language suitable for AWS APG GW import."""

    @api.doc('show api json')
    @api.doc(x_amazon={'x-amazon-apigateway-integration':
        {
            "responses": {
                "default": {
                    "statusCode": "200"
                }
            },
            "uri": "{{flask.fields.url.external}}",
            "passthroughBehavior": "when_no_match",
            "httpMethod": "GET",
            "type": "http_proxy"
        }
    })
    @api.response(200, 'Success')
    def get(self):
        """Get swagger json doc."""

        return flask.jsonify(api.__schema__)
```

which then generates this following:

```
>curl 127.0.0.1:5000/api
 
    "/api": {
      "get": {
        "operationId": "get_dump",
        "responses": {
          "200": {
            "description": "Success"
          }
        },
        "summary": "Get swagger json doc",
        "tags": [
          "Root methods"
        ],
        "x-amazon-apigateway-integration": {
          "httpMethod": "GET",
          "passthroughBehavior": "when_no_match",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "type": "http_proxy",
          "uri": "http://127.0.0.1:5000/api"
        }
      }
    }, 
 ```
This has been tested with AWS APi GW and correctly sets up the API GW with no modification to the generated json.
 
Here's a snippet from simple script which grabs the swagger API output and configures the API GW:

```
def get_api_json(url):
    ...
    response = urllib.urlopen(url_api)
    api_doc = json.loads(response.read())
    ...
    return api_doc

def create_api(api_json, region):
    ...
    api_response = client.import_rest_api(
      failOnWarnings=True,
      body=api_json
    ...

def deploy_api(api_id, stage, api_json, region):

    ...
    client.create_deployment(
      restApiId=api_id,
      stageName=stage,
      cacheClusterEnabled=True,
      cacheClusterSize='1.6',
    ...                        )

```

Complete script here: https://github.com/kkrynitski/flask-restplus/blob/transitional/create_api_gw_sw.py

I'm looking for comments on this, in preparation for a PR. Specifically:
-          the template convention - is "{{ … }}" OK? Or is there a better option?
-          parameter support. I don't want to get sidetracked in supporting lots of other possible parameters. Would this be accepted with only support for {{flask.fields.url.external}}?
This would provide a good starting point for anyone that wanted to add support for other parameters with minor refactoring.
 
My code is here: https://github.com/kkrynitski/flask-restplus,  it's currently working for the API GW case, and I'm working on the unit test coverage before I submit a PR.
 
Open to comments/suggestions/etc.

**Comment by dmulter** [comment]
You should be using API Gateway stage variables for parameter substitutions instead. There's also a convention for how to write your "uri" value in a template style. See the AWS docs for more info.

I don't think there's any need to introduce parameter substitution in this implementation.

**Comment by Kelvinm** [comment]
Hi David,

I appreciate the thought, the API gateway is nifty, but you're making a
very broad assumption that using AWS is an option.  Unfortunately,
enterprises are having a tough time figuring out how to properly secure
their networks and how to properly get their existing code base on AWS so
its much more challenging than you believe.

I appreciate your input though.

**Comment by dmulter** [comment]
Sorry, I should have put my reply directly to kkrynitski as I was responding to his use of proposed templates along with his use case with API Gateway. I didn't want to imply anyone should use it, just that in his case it makes much more sense to implement it the way I'm suggesting.

**Comment by bedge** [comment]
Is there an application for parameter substitutions within vendor extensions that **doesn't** use AWS' API GW?
Just wondering if using the AWS API GW-specific 'stage variables' renders it less generic.

**Comment by dmulter** [comment]
Just FYI @bedge, using the AWS stage vars would not require anything special in flask-restplus vendor field support, as I agree it should not. For this use case, all that would be required is a normal set of JSON field strings. the processing of the stage vars would happen later based on the Swagger JSON, outside the scope of flask-restplus. There's no reason to build anything specific for AWS, it should definitely be completely generic.

My comment back to @kkrynitski was pointing him towards a way to accomplish templated variables without requiring anything in this vendor field support implementation.

**Comment by kkrynitski** [comment]
@dmulter Hi, thank you for pointing on stage variables. I've found out how it work and will remove template variables.

**Comment by kmalyar-tic** [comment]
@Bedge,

Sorry about the confusion, I wasn’t sure what aspect was being addressed.  Yes we have other vendor tags that we are using outside of the AWS API Gateway.  It makes it a bit tougher for us to do.

**Comment by kkrynitski** [comment]
Hi, @noirbizarre, thank you for adding and improving vendor extensions support. Tested it with `x-amazon-apigateway-integration` works perfect.

**Comment by kkrynitski** [comment]
Also have a question: 
I have the code: 
```
@api.route('/status')
class Status(Resource):
    @api.doc('show application status')
    @api.vendor({'amazon-apigateway-integration': {
        "responses": {
            "default": {
                "statusCode": "200"
            }
        },
        "uri": "http://${stageVariables.url}/status",
        "passthroughBehavior": "when_no_match",
        "httpMethod": "GET",
        "type": "http_proxy"
    }
    }) ...
 ```
How to pass api EP  name `/status` to api.vendor `"uri": "http://${stageVariables.url}**_/status_**"` to avoid hard coding?

**Comment by limbosongs** [comment]
Hello, 

Sorry for dragging this up but is there currently a way to support vendor fields in the infoObject?

My current use case would be to support ReDoc x-logo extension:

https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-logo

Thanks!

**Comment by alexpeelman** [comment]
Hi, any view on when a new release will be available that supports this ?

**Comment by woel0007** [comment]
👍
